from django.urls import path
from main.strings import URL
from .views import *

urlpatterns = [
    path(URL.INDEX, index),
    path(URL.Projects.ALLLICENSES, allLicences),
    path(URL.Projects.LICENSE, licence),
    path(URL.Projects.ADDLICENSE, addLicense),
    path(URL.Projects.LICENSE_SEARCH, licenseSearch),
    path(URL.Projects.LICENSES, licences),
    path(URL.Projects.CREATEVALIDATEFIELD, validateField),
    path(URL.Projects.CREATE, create),
    path(URL.Projects.CREATE_FREE, createFree),
    path(URL.Projects.CREATE_MOD, createMod),
    path(URL.Projects.CREATE_CORE, createCore),
    path(URL.Projects.SUBMIT_FREE, submitFreeProject),
    path(URL.Projects.SUBMIT_MOD, submitProject),
    path(URL.Projects.SUBMIT_CORE, submitCoreProject),
    path(URL.Projects.TRASH, trashProject),
    path(URL.Projects.PROFILE_MOD, profileMod),
    path(URL.Projects.PROFILE_FREE, profileFree),
    path(URL.Projects.PROFILE_CORE, profileCore),
    path(URL.Projects.PROFILEEDIT, editProfile),
    path(URL.Projects.MANAGE_ASSETS, manageAssets),
    path(URL.Projects.TOPICSEARCH, topicsSearch),
    path(URL.Projects.TOPICSUPDATE, topicsUpdate),
    path(URL.Projects.TAGSEARCH, tagsSearch),
    path(URL.Projects.TAGSUPDATE, tagsUpdate),
    path(URL.Projects.USER_GH_REPOS, userGithubRepos),
    path(URL.Projects.LINK_FREE_REPO, linkFreeGithubRepo),
    path(URL.Projects.UNLINK_FREE_REPO, unlinkFreeGithubRepo),
    path(URL.Projects.LIVEDATA, liveData),
    path(URL.Projects.GITHUB_EVENTS, githubEventsListener),
    # path(URL.Projects.GITHUB_EVENTS_FREE, githubEventsListenerFree),
    path(URL.Projects.REPORT_CATEGORIES, reportCategories),
    path(URL.Projects.REPORT_PROJECT, reportProject),
    path(URL.Projects.REPORT_SNAPSHOT, reportSnapshot),
    path(URL.Projects.BROWSE_SEARCH, browseSearch),
    path(URL.Projects.SNAPSHOTS, snapshots),
    path(URL.Projects.SNAPSHOT, snapshot),
    path(URL.Projects.TOGGLE_ADMIRATION, toggleAdmiration),
    path(URL.Projects.ADMIRATIONS, projectAdmirations),
    path(URL.Projects.TOGGLE_SNAP_ADMIRATION, toggleSnapAdmiration),
    path(URL.Projects.SNAP_ADMIRATIONS, snapAdmirations),

    path(URL.Projects.INVITE_PROJECT_OWNER, handleOwnerInvitation),
    path(URL.Projects.PROJECT_TRANS_INVITE, projectTransferInvite),
    path(URL.Projects.PROJECT_TRANS_INVITE_ACT, projectTransferInviteAction),

    path(URL.Projects.INVITE_VERPROJECT_MOD, handleVerModInvitation),
    path(URL.Projects.VER_MOD_TRANS_INVITE, projectModTransferInvite),
    path(URL.Projects.VER_MOD_TRANS_INVITE_ACT, projectModTransferInviteAction),

    path(URL.Projects.INVITE_COREPROJECT_MOD, handleCoreModInvitation),
    path(URL.Projects.CORE_MOD_TRANS_INVITE, coreProjectModTransferInvite),
    path(URL.Projects.CORE_MOD_TRANS_INVITE_ACT, coreProjectModTransferInviteAction),

    path(URL.Projects.VER_DEL_REQUEST, verProjectDeleteRequest),
    path(URL.Projects.VER_DEL_REQUEST_ACT, verProjectDeleteRequestAction),
    path(URL.Projects.CORE_DEL_REQUEST, coreProjectDeleteRequest),
    path(URL.Projects.CORE_DEL_REQUEST_ACT, coreProjectDeleteRequestAction),

    path(URL.Projects.FREE_VERIFICATION_REQUEST, freeVerificationRequest),
    path(URL.Projects.CORE_VERIFICATION_REQUEST, coreVerificationRequest),
]
