import re
from datetime import datetime
key = 'VERSION'
value = '1.0.0'
contents = ''
filePath = "main/__version__.py"

try:
    fr = open(filePath, "r")
    contents = fr.read()
    contents = re.sub(r'(\"\"\")+[a-zA-Z0-9,. \n:-]+(\"\"\")+[\n ]',"",contents)
    contents = contents.replace(" ","").strip()
    fr.close()
except: pass

fd = open(filePath, "w")

if contents and contents.__contains__('='):
    version = contents.split("=")
    
    key = version[0]
    version[1] = version[1].strip('\'')
    print(f"Last version: {version[1]}")
    vParts = version[1].replace('v','').split('.')
    if int(vParts[2]) < 9:
        vParts[2] = f"{int(vParts[2])+1}"
    else:
        vParts[2] = "0"
        if int(vParts[1]) < 9:
            vParts[1] = f"{int(vParts[1])+1}"
        else:
            vParts[1] = "0"
            vParts[0] = f"{int(vParts[0])+1}"

    value = f"{'.'.join(vParts)}"

fd.write(f"\"\"\"\nThis is an autogenerated file, do not modify manually.\nLast update {datetime.now()}\n\"\"\"\n\n{key} = \'{value}\'")
fd.close()

print(f"New version: {value}")
