from datetime import datetime
from uuid import uuid4
key = 'REFRESH_STATE'
value = uuid4().hex
filePath = "main/__refresh__.py"
fd = open(filePath, "w")
fd.write(f"\"\"\"\nThis is an autogenerated file, do not modify manually.\nLast update {datetime.now()}\n\"\"\"\n\n{key} = \'{value}\'")
fd.close()

print(f"Refresh state: {value}")
