SUPPORTED_LANGUAGES = (
    ('af', 'Afrikaans'),
    ('ar', 'عربي'),
    ('ast', 'Asturian'),
    ('az', 'Azərbaycanca'),
    ('bg', 'български'),
    ('be', 'Беларуская'),
    ('bn', 'বাংলা'),
    ('br', 'Breton'),
    ('bs', 'Bosanski'),
    ('ca', 'Català'),
    ('cs', 'čeština'),
    ('cy', 'Cymraeg'),
    ('da', 'dansk'),
    ('de', 'Deutsch'),
    ('dsb', 'Lower Sorbian'),
    ('el', 'Ελληνικά'),
    ('en', 'English'),
    ('en-au', 'Australian English'),
    ('en-gb', 'British English'),
    ('eo', 'Esperanto'),
    ('es', 'Español'),
    ('es-ar', 'Argentinian Spanish'),
    ('es-co', 'Colombian Spanish'),
    ('es-mx', 'Mexican Spanish'),
    ('es-ni', 'Nicaraguan Spanish'),
    ('es-ve', 'Venezuelan Spanish'),
    ('et', 'Eestlane'),
    ('eu', 'Euskara'),
    ('fa', 'فارسی'),
    ('fi', 'Suomalainen'),
    ('fr', 'français'),
    ('fy', 'Frysk'),
    ('ga', 'Gaeilge'),
    ('gd', 'Gàidhlig na h-Alba'),
    ('gl', 'Galego'),
    ('he', 'Hebrew'),
    ('hi', 'हिंदी'),
    ('hr', 'Hrvatski'),
    ('hsb', 'Upper Sorbian'),
    ('hu', 'Magyar'),
    ('hy', 'հայերեն'),
    ('ia', 'Interlingua'),
    ('id', 'bahasa Indonesia'),
    ('io', 'Ido'),
    ('is', 'Íslensku'),
    ('it', 'italiano'),
    ('ja', '日本'),
    ('ka', 'ქართული'),
    ('kab', 'Kabyle'),
    ('kk', 'Қазақша'),
    ('km', 'ខ្មែរ'),
    ('kn', 'ಕನ್ನಡ'),
    ('ko', '한국인'),
    ('lb', 'Lëtzebuergesch'),
    ('lt', 'Lietuvių'),
    ('lv', 'Latvietis'),
    ('mk', 'Македонски'),
    ('ml', 'മലയാളം'),
    ('mn', 'Монгол'),
    ('mr', 'मराठी'),
    ('my', 'ဗမာ'),
    ('nb', 'Norwegian Bokmål'),
    ('ne', 'नेपाली'),
    ('nl', 'Nederlands'),
    ('nn', 'Norwegian Nynorsk'),
    ('os', 'Ossetic'),
    ('pa', 'ਪੰਜਾਬੀ'),
    ('pl', 'Polskie'),
    ('pt', 'português'),
    ('pt-br', 'Brazilian Portuguese'),
    ('ro', 'Română'),
    ('ru', 'русский'),
    ('sk', 'Slovenský'),
    ('sl', 'Slovenščina'),
    ('sq', 'Shqiptare'),
    ('sr', 'Српски'),
    ('sr-latn', 'Serbian Latin'),
    ('sv', 'svenska'),
    ('sw', 'Kiswahili'),
    ('ta', 'தமிழ்'),
    ('te', 'తెలుగు'),
    ('th', 'ไทย'),
    ('tr', 'Türk'),
    ('tt', 'Tatar'),
    ('udm', 'Udmurt'),
    ('uk', 'Українська'),
    ('ur', 'اردو'),
    ('uz', "O'zbek"),
    ('vi', 'Tiếng Việt'),
    ('zh-hans', 'Simplified Chinese'),
    ('zh-hant', 'Traditional Chinese'),
)