name: Beta CD

on:
  push:
    branches: [ beta ]
    paths-ignore:
      - "**/*.md"
      - "**/*.bat"
      - "**/*.sh"
      
jobs:
  deploy:
    runs-on: [self-hosted, beta]
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]

    steps:
    - name: Create backup
      run: |
        sudo tar czf _backup_/media.tar.gz media
        sudo rm -f _backup_/media.tar.gz.gpg
        sudo gpg -e -r ${{ secrets.MAILUSER }} _backup_/media.tar.gz
        sudo rm -f _backup_/media.tar.gz
    - name: Merge changes
      run: |
        git pull
    - name: Install dependencies
      run: |
        sudo pip install --upgrade pip
        pip install --upgrade pip
        sudo pip install -r requirements.txt
        pip install -r requirements.txt
    - name: Run migrations
      run: |
        python3 manage.py makemigrations --noinput
        python3 manage.py migrate --noinput
    - name: Release new version
      run: |
        python3 genversion.py
