name: Beta CD

on:
  push:
    branches: [beta]
    paths-ignore:
      - "**/*.md"
      - "**.md"
      - "*.md"
      - "**/*.bat"
      - "**/*.sh"

jobs:
  build:
    runs-on: [self-hosted, beta, building]
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Merge changes
        run: |
          git pull origin beta
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup environment
        run:
          echo "${{ secrets.ENV_DEV }}" > ${{ secrets.ENVPATH }}
      - name: Run migrations
        run: |
          python3 manage.py makemigrations --noinput
          python3 manage.py migrate --noinput
      - name: Synchronise notifications
        run: |
          python3 manage.py syncnotifications --noinput

  deploy:
    needs: [build]
    runs-on: [self-hosted, beta, deployment]
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Create backup
        run: |
          tar czf _backup_/media.tar.gz media
          rm -f _backup_/media.tar.gz.gpg
          gpg -e -r ${{ secrets.MAILUSER }} _backup_/media.tar.gz
          rm -f _backup_/media.tar.gz
      - name: Merge changes
        run: |
          git pull origin beta
      - name: Setup environment
        run:
          echo "${{ secrets.ENV_DEV }}" > ${{ secrets.ENVPATH  }}
      - name: Release new version
        run: |
          ~/Env/beta_knotters/bin/python3 genversion.py
          ~/Env/beta_knotters/bin/python3 manage.py collectstatic --noinput
          ~/Env/beta_knotters/bin/python3 manage.py preparestatics /var/www/beta/knotters/errors/
      - name: Restart services
        run: |
          systemctl --user restart beta.gunicorn.service
          systemctl --user restart beta.cluster0.service
