name: Beta CD

on:
  push:
    branches: [ beta ]
    paths-ignore:
      - "**/*.md"
      - "**/*.bat"
      - "**/*.sh"
      
jobs:
  build:
    runs-on: [self-hosted, beta, building]
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]

    steps:
    - name: Merge changes
      run: |
        git pull origin beta
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: |
        python3 manage.py makemigrations --noinput
        python3 manage.py migrate --noinput

  deploy:
    needs: [build]
    runs-on: [self-hosted, beta, deployment]
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]

    steps:
    - name: Create backup
      run: |
        tar czf _backup_/media.tar.gz media
        rm -f _backup_/media.tar.gz.gpg
        sudo gpg -e -r ${{ secrets.MAILUSER }} _backup_/media.tar.gz
        rm -f _backup_/media.tar.gz
    - name: Merge changes
      run: |
        git pull origin beta
    - name: Release new version
      run: |
        ~/Env/beta_knotters/bin/python3 genversion.py
        ~/Env/beta_knotters/bin/python3 manage.py collectstatic --noinput
        ~/Env/beta_knotters/bin/python3 manage.py preparestatics /var/www/beta/knotters/errors/
    - name: Restart services
      run: |
        sudo systemctl restart beta.gunicorn
        sudo systemctl restart beta.cluster0
