name: Beta CD

on:
  push:
    branches: [beta,dev]
    paths-ignore:
      - "**/*.md"
      - "**.md"
      - "*.md"
      - "**/*.bat"
      - "**/*.sh"
      - "LICENSE"

jobs:
  build_deploy:
    runs-on: [self-hosted, dev, knotters, deployment, django]
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Merge changes
        uses: actions/checkout@v2
        with:
          clean: false
      - name: Install dependencies
        run: |
         /home/ubuntu/dev/bin/pip install --upgrade pip
         /home/ubuntu/dev/bin/pip install -r requirements.txt
      - name: Setup environment
        run:
          echo "${{ secrets.ENV_DEV }}" > main/.env
      - name: Run migrations
        run: |
          /home/ubuntu/dev/bin/python3 manage.py makemigrations --noinput
          /home/ubuntu/dev/bin/python3 manage.py migrate --noinput
 #     - name: Synchronise notifications
  #      run: |
   #       /home/ubuntu/dev/bin/python3 manage.py syncnotifications --noinput
      - name: Release new version
        run: |
          /home/ubuntu/dev/bin/python3 genversion.py
          /home/ubuntu/dev/bin/python3 manage.py collectstatic --noinput
          /home/ubuntu/dev/bin/python3 manage.py preparestatics /var/www/dev/knotters/errors/
      - name: Restart services
        run: |
          sudo systemctl --user --machine=ubuntu@.host restart dev.gunicorn.service
          sudo systemctl --user --machine=ubuntu@.host restart dev.cluster0.service
