name: Server CI Testing

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - ".github/**"
      - "**.json"

jobs:
  testing:
    runs-on: [self-hosted, testing]
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Setup source
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create Environment
      run: |
        echo "${{ secrets.ENV_TEST }}" > ${{ secrets.ENVPATH }}
        touch ${{ secrets.ENVPATH }}
        cp ${{ secrets.ENVPATH }} ${{ secrets.ENVPATH }}.testing
    - name: Run migrations
      run: |
        python3 manage.py makemigrations --noinput
        python3 manage.py migrate --noinput
    - name: Run tests
      run: |
        python3 manage.py test --noinput --verbosity=1 --parallel
    - name: Clear environment
      run: |
        rm -f ${{ secrets.ENVPATH }}
