name: Server CI Testing

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - ".github/**"
      - "**.json"

jobs:
  testing:
    runs-on: [self-hosted, testing]
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Setup source
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create Environment
      run: |
        touch ${{ secrets.ENVPATH }}
        echo "PROJECTKEY=${{ secrets.PROJECTKEY }}" >> ${{ secrets.ENVPATH }}
        echo "PUBNAME=${{ secrets.PUBNAME }}" >> ${{ secrets.ENVPATH }}
        echo "ENV=${{ secrets.ENV }}" >> ${{ secrets.ENVPATH }}
        echo "HOSTS=${{ secrets.HOSTS }}" >> ${{ secrets.ENVPATH }}
        echo "DB_NAME=${{ secrets.DBTESTNAME }}" >> ${{ secrets.ENVPATH }}
        echo "DB_URL=${{ secrets.DBTESTLINK }}" >> ${{ secrets.ENVPATH }}
        echo "DB_USERNAME=${{ secrets.DBTESTUSER }}" >> ${{ secrets.ENVPATH }}
        echo "DB_PASSWORD=${{ secrets.DBTESTPASS }}" >> ${{ secrets.ENVPATH }}
        echo "MAIL_USERNAME=${{ secrets.MAILUSER }}" >> ${{ secrets.ENVPATH }}
        echo "MAIL_PASSWORD=${{ secrets.MAILPASS }}" >> ${{ secrets.ENVPATH }}
        echo "BOTMAIL=${{ secrets.BOTMAIL }}" >> ${{ secrets.ENVPATH }}
        echo "ADMINPATH=${{ secrets.ADMINPATH }}" >> ${{ secrets.ENVPATH }}
        echo "GITHUBBOT_SECRET=${{ secrets.GITHUBBOTTOKEN }}" >> ${{ secrets.ENVPATH }}
        echo "DISCORDBOT_SECRET=${{ secrets.DISCORDBOTTOKEN }}" >> ${{ secrets.ENVPATH }}
        echo "SITE=${{ secrets.SITE }}" >> ${{ secrets.ENVPATH }}
        echo "SENDER_SECRET=${{ secrets.SENDERTOKEN }}" >> ${{ secrets.ENVPATH }}
        echo "MEDIA_URL=${{ secrets.MEDIA_URL }}" >> ${{ secrets.ENVPATH }}
        echo "STATIC_URL=${{ secrets.STATIC_URL }}" >> ${{ secrets.ENVPATH }}
        echo "STATIC_ROOT=${{ secrets.STATIC_ROOT }}" >> ${{ secrets.ENVPATH }}
        echo "SERVER_EMAIL=${{ secrets.SERVER_EMAIL }}" >> ${{ secrets.ENVPATH }}
        echo "GH_HOOK_SECRET=${{ secrets.GH_HOOK_SECRET }}" >> ${{ secrets.ENVPATH }}
        echo "REDIS_LOCATION=${{ secrets.REDIS_LOCATION }}" >> ${{ secrets.ENVPATH }}
        echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> ${{ secrets.ENVPATH }}
        echo "RECAPTCHA_KEY=${{ secrets.RECAPTCHA_KEY }}" >> ${{ secrets.ENVPATH }}
        echo "RECAPTCHA_SECRET=${{ secrets.RECAPTCHA_SECRET }}" >> ${{ secrets.ENVPATH }}
        echo "VAPID_PUBLIC_KEY=${{ secrets.VAPID_PUBLIC_KEY }}" >> ${{ secrets.ENVPATH }}
        echo "VAPID_PRIVATE_KEY=${{ secrets.VAPID_PRIVATE_KEY }}" >> ${{ secrets.ENVPATH }}
        echo "VAPID_ADMIN_MAIL=${{ secrets.VAPID_ADMIN_MAIL }}" >> ${{ secrets.ENVPATH }}
        echo "LOCALE_ABS_PATH=${{ secrets.LOCALE_ABS_PATH }}" >> ${{ secrets.ENVPATH }}
        echo "CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}" >> ${{ secrets.ENVPATH }}
        cp ${{ secrets.ENVPATH }} ${{ secrets.ENVPATH }}.testing
    - name: Run migrations
      run: |
        python3 manage.py makemigrations --noinput
        python3 manage.py migrate --noinput
    - name: Run tests
      run: |
        python3 manage.py test --noinput --verbosity=1 --parallel
    - name: Clear environment
      run: |
        rm -f ${{ secrets.ENVPATH }}
