name: Server CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '**/*.md'
      - '*.md'
      - "LICENSE"
      - 'static/**'
      - '.gitignore'
      - ".github/**"
      - "setup.py"
      - "static.py"
      - "genenv.py"
      - "genversion.py"
      - '**/commands/preparestatics.py'

jobs:
  testing:
    runs-on: [self-hosted, testing, knotters, django]
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Setup source
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        /home/ubuntu/testing/bin/pip install --upgrade pip
        /home/ubuntu/testing/bin/pip install -r requirements.txt
    - name: Create Environment
      run: |
        echo "${{ secrets.ENV_TEST }}" > ${{ secrets.ENVPATH }}
        cp ${{ secrets.ENVPATH }} ${{ secrets.ENVPATH }}.testing
    - name: Run migrations
      run: |
        /home/ubuntu/testing/bin/python3 manage.py makemigrations --noinput
        /home/ubuntu/testing/bin/python3 manage.py migrate --noinput
    - name: Run tests
      run: |
        /home/ubuntu/testing/bin/python3 manage.py test --noinput --verbosity=1 --parallel

  build:
    needs: [testing]
    runs-on: [self-hosted, building, production, knotters, django]
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Merge changes
      uses: actions/checkout@v2
      with:
        clean: false
    - name: Install dependencies
      run: |
        /home/ubuntu/knotters/bin/pip install --upgrade pip
        /home/ubuntu/knotters/bin/pip install -r requirements.txt
    - name: Setup environment
      run: |
        echo "${{ secrets.ENV_PROD }}" > ${{ secrets.ENVPATH }}
    - name: Run migrations
      run: |
        /home/ubuntu/knotters/bin/python3 manage.py makemigrations --noinput
        /home/ubuntu/knotters/bin/python3 manage.py migrate --noinput
    - name: Synchronise notifications
      run: |
        /home/ubuntu/knotters/bin/python3 manage.py syncnotifications --noinput

  deploy:
    needs: [build]
    runs-on: [self-hosted,deployment,production,knotters,django]
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Merge changes
      uses: actions/checkout@v2
      with:
        clean: false
    - name: Setup environment
      run: |
        echo "${{ secrets.ENV_PROD }}" > ${{ secrets.ENVPATH }}
    - name: Restart services
      run: |
        systemctl --machine=ubuntu@.host --user restart knotters.gunicorn.service
        systemctl --machine=ubuntu@.host --user restart knotters.cluster0
#        systemctl --user restart knotters.cluster1
    
