name: Client Static CI

on:
  push:
    branches: [main]
    paths:
      - "static/**"

jobs:
  testing:
    runs-on: [self-hosted, testing, knotters, django]
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Setup source
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        /home/ubuntu/testing/bin/pip install --upgrade pip
        /home/ubuntu/testing/bin/pip install -r requirements.txt
    - name: Create Environment
      run: |
        echo "${{ secrets.ENV_TEST }}" > main/.env
        cp main/.env main/.env.testing
    - name: Run migrations
      run: |
        /home/ubuntu/testing/bin/python3 manage.py makemigrations --noinput
        /home/ubuntu/testing/bin/python3 manage.py migrate --noinput
    - name: Run tests
      run: |
        /home/ubuntu/testing/bin/python3 manage.py test --noinput --verbosity=1 --parallel

  build:
    needs: [testing]
    runs-on: [self-hosted, building, production, knotters, django]
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Merge changes
      uses: actions/checkout@v2
      with:
        clean: false
    - name: Install dependencies
      run: |
        /home/ubuntu/knotters/bin/pip install --upgrade pip
        /home/ubuntu/knotters/bin/pip install -r requirements.txt
    - name: Setup environment
      run: |
        echo "${{ secrets.ENV_PROD }}" > main/.env
    - name: Run migrations
      run: |
        /home/ubuntu/knotters/bin/python3 manage.py makemigrations --noinput
        /home/ubuntu/knotters/bin/python3 manage.py migrate --noinput
   
  client_deploy:
    needs: [build]
    runs-on: [self-hosted,deployment,production,knotters,django]
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Merge changes
      uses: actions/checkout@v2
      with:
        clean: false
    - name: Setup environment
      run: |
        echo "${{ secrets.ENV_PROD }}" > main/.env
    - name: Release new version
      run: |
        /home/ubuntu/knotters/bin/python3 genversion.py
        /home/ubuntu/knotters/bin/python3 manage.py collectstatic --noinput
        /home/ubuntu/knotters/bin/python3 manage.py preparestatics /var/www/knotters/errors/
    - name: Restart server
      run: |
        sudo systemctl --user --machine=ubuntu@.host restart knotters.gunicorn.service
    
