name: Server Methods CI

on:
  push:
    branches: [ main ]
    paths:
      - '**/test_methods.py'
      - '**/methods.py'

jobs:
  testing:
    runs-on: [self-hosted, testing]
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]

    steps:
    - name: Setup source
      uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create Environment
      run: |
        touch ${{ secrets.ENVPATH }}
        echo "PROJECTKEY=${{ secrets.PROJECTKEY }}" >> ${{ secrets.ENVPATH }}
        echo "PUBNAME=${{ secrets.PUBNAME }}" >> ${{ secrets.ENVPATH }}
        echo "ENV=${{ secrets.ENV }}" >> ${{ secrets.ENVPATH }}
        echo "HOSTS=${{ secrets.HOSTS }}" >> ${{ secrets.ENVPATH }}
        echo "DBNAME=${{ secrets.DBTESTNAME }}" >> ${{ secrets.ENVPATH }}
        echo "DBLINK=${{ secrets.DBTESTLINK }}" >> ${{ secrets.ENVPATH }}
        echo "DBUSER=${{ secrets.DBTESTUSER }}" >> ${{ secrets.ENVPATH }}
        echo "DBPASS=${{ secrets.DBTESTPASS }}" >> ${{ secrets.ENVPATH }}
        echo "MAILUSER=${{ secrets.MAILUSER }}" >> ${{ secrets.ENVPATH }}
        echo "MAILPASS=${{ secrets.MAILPASS }}" >> ${{ secrets.ENVPATH }}
        echo "BOTMAIL=${{ secrets.BOTMAIL }}" >> ${{ secrets.ENVPATH }}
        echo "ADMINPATH=${{ secrets.ADMINPATH }}" >> ${{ secrets.ENVPATH }}
        echo "GITHUBBOTTOKEN=${{ secrets.GITHUBBOTTOKEN }}" >> ${{ secrets.ENVPATH }}
        echo "DISCORDBOTTOKEN=${{ secrets.DISCORDBOTTOKEN }}" >> ${{ secrets.ENVPATH }}
        echo "SITE=${{ secrets.SITE }}" >> ${{ secrets.ENVPATH }}
        echo "SENDERTOKEN=${{ secrets.SENDERTOKEN }}" >> ${{ secrets.ENVPATH }}
        echo "MEDIA_URL=${{ secrets.MEDIA_URL }}" >> ${{ secrets.ENVPATH }}
        echo "STATIC_URL=${{ secrets.STATIC_URL }}" >> ${{ secrets.ENVPATH }}
        echo "STATIC_ROOT=${{ secrets.STATIC_ROOT }}" >> ${{ secrets.ENVPATH }}
        echo "SERVER_EMAIL=${{ secrets.SERVER_EMAIL }}" >> ${{ secrets.ENVPATH }}
        echo "GH_HOOK_SECRET=${{ secrets.GH_HOOK_SECRET }}" >> ${{ secrets.ENVPATH }}
        echo "REDIS_LOCATION=${{ secrets.REDIS_LOCATION }}" >> ${{ secrets.ENVPATH }}
        echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}" >> ${{ secrets.ENVPATH }}
        echo "RECAPTCHA_KEY=${{ secrets.RECAPTCHA_KEY }}" >> ${{ secrets.ENVPATH }}
        echo "RECAPTCHA_SECRET=${{ secrets.RECAPTCHA_SECRET }}" >> ${{ secrets.ENVPATH }}
        echo "VAPID_PUBLIC_KEY=${{ secrets.VAPID_PUBLIC_KEY }}" >> ${{ secrets.ENVPATH }}
        echo "VAPID_PRIVATE_KEY=${{ secrets.VAPID_PRIVATE_KEY }}" >> ${{ secrets.ENVPATH }}
        echo "VAPID_ADMIN_MAIL=${{ secrets.VAPID_ADMIN_MAIL }}" >> ${{ secrets.ENVPATH }}
        echo "LOCALE_ABS_PATH=${{ secrets.LOCALE_ABS_PATH }}" >> ${{ secrets.ENVPATH }}
        echo "CORS_ALLOWED_ORIGINS=${{ secrets.CORS_ALLOWED_ORIGINS }}" >> ${{ secrets.ENVPATH }}
    - name: Run migrations
      run: |
        python3 manage.py makemigrations --noinput
        python3 manage.py migrate --noinput
    - name: Run tests
      run: |
        python3 manage.py test --noinput --verbosity=1 --parallel --exclude-tag=model
    - name: Clear environment
      run: |
        rm -f ${{ secrets.ENVPATH }}

  build:
    needs: [testing]
    runs-on: [self-hosted, building, production]
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]

    steps:
    - name: Create backup
      run: |
        mongodump --forceTableScan --uri="${{ secrets.DBBACKUPLINK }}" -o _backup_
        tar czf _backup_/${{ secrets.DBNAME }}.tar.gz _backup_/${{ secrets.DBNAME }}
        rm -f _backup_/${{ secrets.DBNAME }}.tar.gz.gpg
        gpg -e -r ${{ secrets.MAILUSER }} _backup_/${{ secrets.DBNAME }}.tar.gz
        rm -f -r _backup_/${{ secrets.DBNAME }}
        rm -f _backup_/${{ secrets.DBNAME }}.tar.gz
        drive push -force -no-prompt -destination backups ~/drive/${{ secrets.DBNAME }}.tar.gz.gpg
    - name: Merge changes
      run: |
        git pull --depth=100
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup environment
      run: |
        rm -f ${{ secrets.ENVPATH }}
        gpg --pinentry-mode loopback --passphrase "${{ secrets.KNOTTERSBOTGPG }}" -o ${{ secrets.ENVPATH }} -d ${{ secrets.ENVGPGPATH }}
    - name: Run migrations
      run: |
        python3 manage.py makemigrations --noinput
        python3 manage.py migrate --noinput
    - name: Clear environment
      run: |
        rm -f ${{ secrets.ENVPATH }}

  deploy:
    needs: [build]
    runs-on: [self-hosted,deployment,production]
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]

    steps:
    - name: Create backup
      run: |
        tar czf _backup_/media.tar.gz media
        rm -f _backup_/media.tar.gz.gpg
        gpg -e -r ${{ secrets.MAILUSER }} _backup_/media.tar.gz
        rm -f _backup_/media.tar.gz
        drive push -force -no-prompt -destination backups ~/drive/media.tar.gz.gpg
    - name: Merge changes
      run: |
        git pull origin main --depth=100
    - name: Restart services
      run: |
        sudo systemctl restart knotters.gunicorn
        sudo systemctl restart knotters.cluster0
#         sudo systemctl restart knotters.cluster1
    - name: Clear environment
      run: |
        rm -f ${{ secrets.ENVPATH }}