name: Knotters Django CI Testing

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - "README.md"
      - "CONTRIBUTING.md"

jobs:
  testing:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Setup Environment
      run: |
        touch .env
        echo "PROJECTKEY=${{ secrets.PROJECTKEY }}" >> .env
        echo "PUBNAME=${{ secrets.PUBNAME }}" >> .env
        echo "ENV=${{ secrets.ENV }}" >> .env
        echo "HOSTS=${{ secrets.HOSTS }}" >> .env
        echo "DBNAME=${{ secrets.DBNAME }}" >> .env
        echo "DBLINK=${{ secrets.DBLINK }}" >> .env
        echo "DBUSER=${{ secrets.DBUSER }}" >> .env
        echo "DBPASS=${{ secrets.DBPASS }}" >> .env
        echo "MAILUSER=${{ secrets.MAILUSER }}" >> .env
        echo "MAILPASS=${{ secrets.MAILPASS }}" >> .env
        echo "ADMINPATH=${{ secrets.ADMINPATH }}" >> .env
        echo "CORSLIST=${{ secrets.CORSLIST }}" >> .env
        echo "COOKIEDOM=${{ secrets.COOKIEDOM }}" >> .env
    - name: Unit Testing
      run: |
        python manage.py test
