name: Locale CI

on:
  push:
    branches: [ main ]
    paths:
      - "locale/**"

jobs:
  locale_deploy:
    runs-on: [self-hosted, deployment]
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]

    steps:
    - name: Merge changes
      run: |
        sudo git pull --depth=20
    - name: Compile messages
      run: |
        python3 manage.py compilemessages
