name: Knotters Client Views CI

on:
  push:
    branches: [ main ]
    paths:
      - "!static/**"
      - "!main/**"
      - "!moderation/**"
      - "!compete/**"
      - "!people/**"
      - "!projects/**"
      - "!*.py"
      - "templates/**"

jobs:
  client_view_deploy:
    runs-on: [self-hosted, deployment]
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.8]

    steps:
    - name: Merge changes
      run: |
        sudo git pull --depth=10
      working-directory: ${{ secrets.WORKINGDIR }}
