name: Knotters Django CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/workflows/main-pr.yml"
      - "README.md"
      - "CONTRIBUTING.md"
      - "main/.env.example"

jobs:
  testing:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
    steps:
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Unit Testing
      run: |
        python manage.py test

  building:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - name: Fetch & Merge changes
      run: git pull
      working-directory: C:/Users/Administrator/actions-runner/knotters/knotters/knotters
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
